package com.ts.spm.bizs.entity.jzpmq;

import java.util.Date;

public class JudgePictureResultInfo1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.FIRST_TIME
     *
     * @mbg.generated
     */
    private Date firstTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.MISSION_ID
     *
     * @mbg.generated
     */
    private String missionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.POINTID
     *
     * @mbg.generated
     */
    private String pointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.SN
     *
     * @mbg.generated
     */
    private String sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.JUDGE_PICTURE_USER_ID
     *
     * @mbg.generated
     */
    private String judgePictureUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.LOCATION_OF_SUSPECTED_ITEMS
     *
     * @mbg.generated
     */
    private String locationOfSuspectedItems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.SUSPECTED_CONTRABAND_TYPE
     *
     * @mbg.generated
     */
    private String suspectedContrabandType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR1
     *
     * @mbg.generated
     */
    private String attr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR2
     *
     * @mbg.generated
     */
    private String attr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR3
     *
     * @mbg.generated
     */
    private String attr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR4
     *
     * @mbg.generated
     */
    private String attr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR5
     *
     * @mbg.generated
     */
    private String attr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR6
     *
     * @mbg.generated
     */
    private String attr6;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JUDGE_PICTURE_RESULT_INFO_1
     *
     * @mbg.generated
     */
    public JudgePictureResultInfo1(String id, Date firstTime, String missionId, String pointid, String sn, String judgePictureUserId, String locationOfSuspectedItems, String suspectedContrabandType, Date createTime, Date updateTime, String memo, String attr1, String attr2, String attr3, String attr4, String attr5, String attr6) {
        this.id = id;
        this.firstTime = firstTime;
        this.missionId = missionId;
        this.pointid = pointid;
        this.sn = sn;
        this.judgePictureUserId = judgePictureUserId;
        this.locationOfSuspectedItems = locationOfSuspectedItems;
        this.suspectedContrabandType = suspectedContrabandType;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.memo = memo;
        this.attr1 = attr1;
        this.attr2 = attr2;
        this.attr3 = attr3;
        this.attr4 = attr4;
        this.attr5 = attr5;
        this.attr6 = attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JUDGE_PICTURE_RESULT_INFO_1
     *
     * @mbg.generated
     */
    public JudgePictureResultInfo1() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ID
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ID
     *
     * @param id the value for JUDGE_PICTURE_RESULT_INFO_1.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.FIRST_TIME
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.FIRST_TIME
     *
     * @mbg.generated
     */
    public Date getFirstTime() {
        return firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.FIRST_TIME
     *
     * @param firstTime the value for JUDGE_PICTURE_RESULT_INFO_1.FIRST_TIME
     *
     * @mbg.generated
     */
    public void setFirstTime(Date firstTime) {
        this.firstTime = firstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.MISSION_ID
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.MISSION_ID
     *
     * @mbg.generated
     */
    public String getMissionId() {
        return missionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.MISSION_ID
     *
     * @param missionId the value for JUDGE_PICTURE_RESULT_INFO_1.MISSION_ID
     *
     * @mbg.generated
     */
    public void setMissionId(String missionId) {
        this.missionId = missionId == null ? null : missionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.POINTID
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.POINTID
     *
     * @mbg.generated
     */
    public String getPointid() {
        return pointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.POINTID
     *
     * @param pointid the value for JUDGE_PICTURE_RESULT_INFO_1.POINTID
     *
     * @mbg.generated
     */
    public void setPointid(String pointid) {
        this.pointid = pointid == null ? null : pointid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.SN
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.SN
     *
     * @mbg.generated
     */
    public String getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.SN
     *
     * @param sn the value for JUDGE_PICTURE_RESULT_INFO_1.SN
     *
     * @mbg.generated
     */
    public void setSn(String sn) {
        this.sn = sn == null ? null : sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.JUDGE_PICTURE_USER_ID
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.JUDGE_PICTURE_USER_ID
     *
     * @mbg.generated
     */
    public String getJudgePictureUserId() {
        return judgePictureUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.JUDGE_PICTURE_USER_ID
     *
     * @param judgePictureUserId the value for JUDGE_PICTURE_RESULT_INFO_1.JUDGE_PICTURE_USER_ID
     *
     * @mbg.generated
     */
    public void setJudgePictureUserId(String judgePictureUserId) {
        this.judgePictureUserId = judgePictureUserId == null ? null : judgePictureUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.LOCATION_OF_SUSPECTED_ITEMS
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.LOCATION_OF_SUSPECTED_ITEMS
     *
     * @mbg.generated
     */
    public String getLocationOfSuspectedItems() {
        return locationOfSuspectedItems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.LOCATION_OF_SUSPECTED_ITEMS
     *
     * @param locationOfSuspectedItems the value for JUDGE_PICTURE_RESULT_INFO_1.LOCATION_OF_SUSPECTED_ITEMS
     *
     * @mbg.generated
     */
    public void setLocationOfSuspectedItems(String locationOfSuspectedItems) {
        this.locationOfSuspectedItems = locationOfSuspectedItems == null ? null : locationOfSuspectedItems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.SUSPECTED_CONTRABAND_TYPE
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.SUSPECTED_CONTRABAND_TYPE
     *
     * @mbg.generated
     */
    public String getSuspectedContrabandType() {
        return suspectedContrabandType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.SUSPECTED_CONTRABAND_TYPE
     *
     * @param suspectedContrabandType the value for JUDGE_PICTURE_RESULT_INFO_1.SUSPECTED_CONTRABAND_TYPE
     *
     * @mbg.generated
     */
    public void setSuspectedContrabandType(String suspectedContrabandType) {
        this.suspectedContrabandType = suspectedContrabandType == null ? null : suspectedContrabandType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.CREATE_TIME
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.CREATE_TIME
     *
     * @param createTime the value for JUDGE_PICTURE_RESULT_INFO_1.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.UPDATE_TIME
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.UPDATE_TIME
     *
     * @param updateTime the value for JUDGE_PICTURE_RESULT_INFO_1.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.MEMO
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.MEMO
     *
     * @param memo the value for JUDGE_PICTURE_RESULT_INFO_1.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR1
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR1
     *
     * @mbg.generated
     */
    public String getAttr1() {
        return attr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR1
     *
     * @param attr1 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR1
     *
     * @mbg.generated
     */
    public void setAttr1(String attr1) {
        this.attr1 = attr1 == null ? null : attr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR2
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR2
     *
     * @mbg.generated
     */
    public String getAttr2() {
        return attr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR2
     *
     * @param attr2 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR2
     *
     * @mbg.generated
     */
    public void setAttr2(String attr2) {
        this.attr2 = attr2 == null ? null : attr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR3
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR3
     *
     * @mbg.generated
     */
    public String getAttr3() {
        return attr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR3
     *
     * @param attr3 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR3
     *
     * @mbg.generated
     */
    public void setAttr3(String attr3) {
        this.attr3 = attr3 == null ? null : attr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR4
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR4
     *
     * @mbg.generated
     */
    public String getAttr4() {
        return attr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR4
     *
     * @param attr4 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR4
     *
     * @mbg.generated
     */
    public void setAttr4(String attr4) {
        this.attr4 = attr4 == null ? null : attr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR5
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR5
     *
     * @mbg.generated
     */
    public String getAttr5() {
        return attr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR5
     *
     * @param attr5 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR5
     *
     * @mbg.generated
     */
    public void setAttr5(String attr5) {
        this.attr5 = attr5 == null ? null : attr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR6
     *
     * @return the value of JUDGE_PICTURE_RESULT_INFO_1.ATTR6
     *
     * @mbg.generated
     */
    public String getAttr6() {
        return attr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JUDGE_PICTURE_RESULT_INFO_1.ATTR6
     *
     * @param attr6 the value for JUDGE_PICTURE_RESULT_INFO_1.ATTR6
     *
     * @mbg.generated
     */
    public void setAttr6(String attr6) {
        this.attr6 = attr6 == null ? null : attr6.trim();
    }
}