logging:
  level:
    #        tk.mybatis: DEBUG
    com.ts.spm.bizs: INFO
server:
  port: 5006

spring:
  application:
    name: spm-bizs
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:10.16.100.3}:${MYSQL_PORT:63306}/spm_sys?useUnicode=true&characterEncoding=UTF8
    username: telesounduser
    password: xatelesoundusersx#$1
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandonedTimeout: 1800
  redis:
    database: 1
    host: ${REDIS_HOST:10.16.100.3}
    port: ${REDIS_PORT:6379}
    password: sx123456
    pool:
      max-active: 20

# 配置数据库
mybatis:
  mapper-locations: "classpath*:mapper/**/*.xml"
  configuration:
    settings:
      #      返回空字段
      callSettersOnNulls: true

# 配置swagger
swagger:
  enabled: true
  base-package: com.ts.spm.bizs
  title: smp-bizs
  version: 1.0.0.SNAPSHOT
  description: 业务管理
  contact:
    name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: spm-bizs
    secret: 123456
    token-header: client-token

### spm-gis
gisTilePath: /usr/local/spm/map/map.mbtiles

### spm-tool
ftp:
  ftpPath: /usr/local/ftp/
  ftpDa: /spm/da/
  ftpOther: /spm/other/
  ftpRootDir: /data/ftpdir
  ftpLocal: D:/test
  ftpHost: 10.16.100.14
  ftpPort: 21
  ftpUserName: ftpuser
  ftpPassword: sx123456
